# Get price data

In [1]:
import requests
import pandas as pd

In [2]:
def get_crypto_price(symbol, interval, days):
    api_key = 'ffe545e905814682a6078d6a3850b6a2'
    api_url = f'https://api.twelvedata.com/time_series?symbol={symbol}&exchange=Binance&interval={interval}&outputsize={days}&apikey={api_key}'
    raw = requests.get(api_url).json()
    df = pd.DataFrame(raw['values']).set_index('datetime')
    df = df.iloc[::-1]
    return df

In [6]:
# Get 5 years worth of data
df = get_crypto_price('BTC/USD', '1day', 1825)  # number of days
df

                   open         high          low        close
datetime
2017-08-28   4306.12988   4399.81982   4271.02979   4386.68994
2017-08-29   4386.68994   4625.85010   4313.54980   4587.47998
2017-08-30   4587.47998   4647.50977   4416.04980   4555.14014
2017-08-31   4555.14014   4745.41992   4555.14014   4724.89014
2017-09-01   4724.89014   4885.54980   4654.87988   4834.91016
...                 ...          ...          ...          ...
2021-09-17  47761.91016  48149.98828  46789.60938  47277.91016
2021-09-18  47312.23047  48754.42969  47066.89062  48304.98828
2021-09-19  48294.35156  48338.62109  46865.53906  47236.53906
2021-09-20  47284.10156  47324.46094  42532.69141  42968.23047
2021-09-21  43014.00000  43620.60938  40381.76953  42673.44141

[1486 rows x 4 columns]

In [7]:
df.to_csv('BTC_5Years.csv', index=False)